[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = "0.140.2"
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v2"
