baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-compatibility'

[module]
  # Build and serve using local mod-compatibility clone declared in the named Hugo workspace:
  workspace = "mod-compatibility.work"
  [[module.imports]]
    path = "github.com/gethinode/mod-compatibility"
  [[module.imports.mounts]]
    source = "dist"
    target = "static"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"